### ISSUE TITLE
服务机器人（给用户发送消息等）

### ISSUE THREAD

**Issue by putiaopi** [Muriel2000/--pin#1]

**Comment by Muriel2000** [comment]
我们需要实现的功能：将得到的打车订单进行处理，根据时间，地点，推送给用户
如果是给用户发消息的话，大致情况划分：
1）我们自己搜寻群聊天得到的信息，消息推送
小颜搜寻，转发消息，储存起来---->不知道占用内存大不大
崔，旸过滤消息----->达成一定格式，比如QQ用户名，出发地，到达地，时间
小邹和小朱消息匹配，地点一定范围内，时间一定范围内配对，再由我们的QQ机器人发送给用户
2）用户主动发消息给我们机器人
小邹，小朱自己匹配成需要的格式，比如QQ用户名，出发地，到达地，时间
每天固定时间推送？匹配到用户就推送？

**Comment by Muriel2000** [comment]
对于匹配，即消息整理，时间，地点为标准归类？

 @消息推送机器人的编写

**Comment by Muriel2000** [comment]
那个判断是否卖出的，现阶段可以不用太考虑，只根据时间判断是否下架，后面可以加一个查询该用户的最近记录，一般人卖出后觉得来找他的人太多了就会发一个卖完了，或者卖出去了这种的话，以这个为判断决定是否下架。//或者直接把卖家最近一段时间的发言都发给用户，让用户自己判断

**Comment by Muriel2000** [comment]
> 
> 
> 那个判断是否卖出的，现阶段可以不用太考虑，只根据时间判断是否下架，后面可以加一个查询该用户的最近记录，一般人卖出后觉得来找他的人太多了就会发一个卖完了，或者卖出去了这种的话，以这个为判断决定是否下架。//或者直接把卖家最近一段时间的发言都发给用户，让用户自己判断

注意卖家推出多个商品和一个商品的处理
